/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import cliente.Cliente;
import controller.leilao.ControlePrincipal;
import exceptions.lance.ValorLanceInvalidoException;
import java.io.IOException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import lance.Lance;
import produto.Produto;

/**
 *
 * @author Vitor
 */
public class InterfaceDoClienteForm extends javax.swing.JFrame {

    private ControlePrincipal _controControlePrincipal;

    /**
     * Creates new form InterfaceDoClienteForm
     */
    public InterfaceDoClienteForm() {
        initComponents();
        try {
            this._controControlePrincipal = new ControlePrincipal();
        } catch (NotBoundException | IOException ex) {
            mensagemDeErro(ex);
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNomeCliente = new javax.swing.JTextField();
        btConectar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ltProdutos = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfLanceAtual = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfTempoRestante = new javax.swing.JTextField();
        btFazerUmLance = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfDonoDoLance = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Leilão de Pordutos"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));

        jLabel1.setText("Nome:");

        btConectar.setText("Conectar");
        btConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btConectar)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConectar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos"));

        ltProdutos.setEnabled(false);
        ltProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ltProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ltProdutos);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Controles"));

        jLabel2.setText("Lance Atual: R$");

        tfLanceAtual.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        tfLanceAtual.setEnabled(false);

        jLabel3.setText("Tempo Restante:");

        tfTempoRestante.setDisabledTextColor(new java.awt.Color(255, 102, 0));
        tfTempoRestante.setEnabled(false);

        btFazerUmLance.setForeground(new java.awt.Color(0, 153, 0));
        btFazerUmLance.setText("Fazer um Lance!");
        btFazerUmLance.setEnabled(false);
        btFazerUmLance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFazerUmLanceActionPerformed(evt);
            }
        });

        btSair.setForeground(new java.awt.Color(255, 0, 0));
        btSair.setText("Sair");
        btSair.setEnabled(false);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jLabel4.setText("Dono do lance:");

        tfDonoDoLance.setDisabledTextColor(new java.awt.Color(0, 51, 255));
        tfDonoDoLance.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btFazerUmLance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(btSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfLanceAtual)
                            .addComponent(tfTempoRestante)
                            .addComponent(tfDonoDoLance))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfLanceAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfDonoDoLance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfTempoRestante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btFazerUmLance)
                .addGap(45, 45, 45)
                .addComponent(btSair)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConectarActionPerformed
        Cliente clienteAux = new Cliente(this.tfNomeCliente.getText());
        try {
            this._controControlePrincipal.novoCliente(clienteAux);
            this.ltProdutos.setModel(converterListaDeProdutosParaDefaultListModel(this._controControlePrincipal.getListaDeProdutos()));
            setEnableDosElementos(true);
        } catch (RemoteException ex) {
            mensagemDeErro(ex);

        }
    }//GEN-LAST:event_btConectarActionPerformed

    private void ltProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ltProdutosMouseClicked
        if (evt.getClickCount() > 1) {
            try {
                getProdutoDetalhes();
            } catch (RemoteException ex) {
                mensagemDeErro(ex);

            }
        }
        try {
            Produto produto = getProdutoSelecionado();
            Lance lance = this._controControlePrincipal.getlanceAtualDoProduto(produto);
            if (lance == null) {
                this.tfLanceAtual.setText(Double.toString(produto.getLanceInicial()));
                this.tfDonoDoLance.setText("-------");
            } else {
                this.tfLanceAtual.setText(Double.toString(lance.getValor()));
                this.tfDonoDoLance.setText(lance.getCliente().getNome());
            }

        } catch (RemoteException ex) {
            mensagemDeErro(ex);
        }

    }//GEN-LAST:event_ltProdutosMouseClicked

    private void btFazerUmLanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFazerUmLanceActionPerformed
        if (this.ltProdutos.isSelectionEmpty()) {
            mensagemDeErro(new Exception("Nenhum produto selecionado!"));
        } else {
            double valorLance;
            try {
                Produto produto = getProdutoSelecionado();
                valorLance = Double.parseDouble(JOptionPane.showInputDialog(rootPane, "Valor do Lance:", "Fazer um Lance", JOptionPane.INFORMATION_MESSAGE));
                Lance novoLance = new Lance(this._controControlePrincipal.getClienteAtual(), produto, valorLance);
                novoLance = this._controControlePrincipal.fazerUmLance(novoLance);
                if(novoLance.getId() != 0){
                    JOptionPane.showMessageDialog(rootPane, "Lance realizado com sucesso!", "Lance realizado!", JOptionPane.INFORMATION_MESSAGE);
                }

            } catch (RemoteException | ValorLanceInvalidoException ex) {
                mensagemDeErro(ex);
            }
        }
    }//GEN-LAST:event_btFazerUmLanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceDoClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceDoClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceDoClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceDoClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceDoClienteForm().setVisible(true);
            }
        });
    }

    private void mensagemDeErro(Exception ex) {
        JOptionPane.showMessageDialog(rootPane, "Erro: " + ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }

    private void setEnableDosElementos(boolean enabled) {
        this.ltProdutos.setEnabled(enabled);
        this.btFazerUmLance.setEnabled(enabled);
        this.btSair.setEnabled(enabled);
        this.btConectar.setEnabled(!enabled);
    }

    private DefaultListModel<String> converterListaDeProdutosParaDefaultListModel(List<Produto> listaDeprodutos) {
        DefaultListModel<String> defaultList = new DefaultListModel<>();
        listaDeprodutos.forEach((produto) -> {
            defaultList.addElement(produto.getNome());
        });
        return defaultList;
    }

    private Produto getProdutoSelecionado() throws RemoteException {
        int index = this.ltProdutos.getSelectedIndex();
        return this._controControlePrincipal.getProduto(index);
    }

    private void getProdutoDetalhes() throws RemoteException {
        Produto produto = getProdutoSelecionado();
        String detalhes = "Produto: " + produto.getNome() + "\n"
                + "\tDescrição: " + produto.getDescricao() + "\n"
                + "\tPreço Inicial: R$ " + produto.getLanceInicial();
        JOptionPane.showMessageDialog(rootPane, detalhes, "Detalhes do Produto", JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConectar;
    private javax.swing.JButton btFazerUmLance;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> ltProdutos;
    private javax.swing.JTextField tfDonoDoLance;
    private javax.swing.JTextField tfLanceAtual;
    private javax.swing.JTextField tfNomeCliente;
    private javax.swing.JTextField tfTempoRestante;
    // End of variables declaration//GEN-END:variables
}
